Make missing_header also trigger on blah.H not found, not just blah.h.
Generalize badc++ case: s/ISO C++ does not support/ISO C++/ .

Fine-tune clang a bit by removing the following false positives:
  error: expected.*(at end of declaration|expression|identifier)
  error: invalid (argument type|integral value|operand|token|use of a cast|value)
  error:.*not supported

Remove some false positives for assumes_gcc (would fire on any fetch
failure for a gcc component)

Cope with some POLA in runaway_process.